# Numpy

In [1]:
import numpy as np

In [2]:
L = [1800, 1500, 2200, 3000,5000]
np.mean(L)

2700.0

In [3]:
x = [-2, -1, 1, 2]
print("The absolute value of the vector x is: ", np.abs(x))
print("The exponential of the vector x is:: ", np.exp(x))
print("The logarithm of the vector : ", np.log(np.abs(x)))

The absolute value of the vector x is:  [2 1 1 2]
The exponential of the vector x is::  [0.13533528 0.36787944 2.71828183 7.3890561 ]
The logarithm of the vector :  [0.69314718 0.         0.         0.69314718]


In [ ]:
# Creating an array from a list
#L = [[-5, 6.9, 34, 0],[-2, -1, 1, 2]]
L = [-5, 6.9, 34, 0,-2, -1, 1, 2]
L_array = np.array(L)
L_array.shape #return the dimension of the array in a tuple

(8,)

In [ ]:
# Creating an array directly
A = np.random.randint(0,100,[2,3])
B = np.random.randint(0,10,[3,2])
print(A)
print(B)
# Example of a dot product betweeen two matrices
print(np.dot(A,B)) #or np.dot(A@B)
#B = [[-5, 6.9, 34, 0],[-2, -1, 1, 2]]
C = np.random.randint(0,10,[2,5])
print(np.dot(np.dot(A,B),C))

[[47 41 28]
 [82 96 44]]
[[5 4]
 [8 6]
 [4 4]]
[[ 675  546]
 [1354 1080]]


In [ ]:
# Getting the type of the elements of the array
L_array.dtype

dtype('float64')

In [7]:
# Array Indexing
# accessing the fifth element of a one-dimensionnal arrray
print(L_array[4])
# accessing all elements starting the 3rd
print(L_array[2:])
# accessing the first three elements
print(L_array[:3])
# every second element
print(L_array[::2])

-2.0
[34.  0. -2. -1.  1.  2.]
[-5.   6.9 34. ]
[-5. 34. -2.  1.]


In [ ]:
# Conditional Indexing
A = np.random.randint(0,100,[2,3])
print(A)
print(A[A>1]) #checking if each element of the matrix is >1 
#the result is an array of type boolean
#the condition is put into the square brackets

#B= A>1
#print(B.dtype)

L_array[(L_array > 2000)]
print((L_array > 2000))
# array([2200, 2172])
L_array[(L_array > 2000) & (L_array < 3000)]
# array([2200, 2172])

[[51 63 70]
 [17  6 71]]
[51 63 70 17  6 71]
[False False False False False False False False]


array([], dtype=float64)

In [97]:
E = np.linspace(1,10,40)
print(E.shape)

(40,)


In [ ]:
M_array = np.random([4,5])
print(M_array)
M_array[0][0] #element in position 0,0
M_array[0][4]
M_array[:2, 0]  #element in position (x,y) = (0,0), (0,1)
M_array[:,:3] #all the elements of the first 3 columns